# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 413)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(160, 30, 231, 18))
        self.title.setObjectName("title")
        self.counter = QtWidgets.QLabel(Form)
        self.counter.setGeometry(QtCore.QRect(210, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("C059")
        font.setPointSize(20)
        self.counter.setFont(font)
        self.counter.setFrameShape(QtWidgets.QFrame.Box)
        self.counter.setAlignment(QtCore.Qt.AlignCenter)
        self.counter.setObjectName("counter")
        self.button_click = QtWidgets.QPushButton(Form)
        self.button_click.setGeometry(QtCore.QRect(150, 200, 201, 71))
        self.button_click.setObjectName("button_click")
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(190, 300, 121, 101))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("My_First_App/image/cola.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Contador de clicks"))
        self.title.setText(_translate("Form", "Contador de clicks"))
        self.counter.setText(_translate("Form", "0"))
        self.button_click.setText(_translate("Form", "Haz click aqui"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
