from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 420)
        MainWindow.setMinimumSize(QtCore.QSize(360, 400))
        MainWindow.setMaximumSize(QtCore.QSize(370, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contenedor = QtWidgets.QFrame(self.centralwidget)
        self.contenedor.setEnabled(True)
        self.contenedor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.contenedor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.contenedor.setObjectName("contenedor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.contenedor)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_visor = QtWidgets.QFrame(self.contenedor)
        self.frame_visor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_visor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_visor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_visor.setObjectName("frame_visor")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_visor)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_title = QtWidgets.QLabel(self.frame_visor)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Bengali")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout.addWidget(self.lbl_title, 0, 0, 1, 1)
        self.edit_pantalla = QtWidgets.QLineEdit(self.frame_visor)
        self.edit_pantalla.setAlignment(QtCore.Qt.AlignRight)
        self.edit_pantalla.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.edit_pantalla.setObjectName("edit_pantalla")
        self.gridLayout.addWidget(self.edit_pantalla, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_visor, 0, 0, 1, 1)
        self.frame_botones = QtWidgets.QFrame(self.contenedor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_botones.sizePolicy().hasHeightForWidth())
        self.frame_botones.setSizePolicy(sizePolicy)
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_botones.setObjectName("frame_botones")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_botones)
        self.gridLayout_3.setContentsMargins(0, 8, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_4 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout_3.addWidget(self.btn_4, 3, 0, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout_3.addWidget(self.btn_1, 4, 0, 1, 1)
        self.btn_igual = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_igual.sizePolicy().hasHeightForWidth())
        self.btn_igual.setSizePolicy(sizePolicy)
        self.btn_igual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_igual.setObjectName("btn_igual")
        self.gridLayout_3.addWidget(self.btn_igual, 5, 4, 1, 2)
        self.btn_PC = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_PC.sizePolicy().hasHeightForWidth())
        self.btn_PC.setSizePolicy(sizePolicy)
        self.btn_PC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_PC.setObjectName("btn_PC")
        self.gridLayout_3.addWidget(self.btn_PC, 0, 4, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout_3.addWidget(self.btn_8, 2, 2, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        self.btn_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout_3.addWidget(self.btn_0, 5, 2, 1, 1)
        self.btn_point = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_point.sizePolicy().hasHeightForWidth())
        self.btn_point.setSizePolicy(sizePolicy)
        self.btn_point.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_point.setObjectName("btn_point")
        self.gridLayout_3.addWidget(self.btn_point, 5, 0, 1, 1)
        self.btn_suma = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_suma.sizePolicy().hasHeightForWidth())
        self.btn_suma.setSizePolicy(sizePolicy)
        self.btn_suma.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_suma.setObjectName("btn_suma")
        self.gridLayout_3.addWidget(self.btn_suma, 4, 5, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout_3.addWidget(self.btn_2, 4, 2, 1, 1)
        self.btn_borrar = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_borrar.sizePolicy().hasHeightForWidth())
        self.btn_borrar.setSizePolicy(sizePolicy)
        self.btn_borrar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_borrar.setObjectName("btn_borrar")
        self.gridLayout_3.addWidget(self.btn_borrar, 0, 0, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout_3.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout_3.addWidget(self.btn_9, 2, 4, 1, 1)
        self.btn_PA = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_PA.sizePolicy().hasHeightForWidth())
        self.btn_PA.setSizePolicy(sizePolicy)
        self.btn_PA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_PA.setObjectName("btn_PA")
        self.gridLayout_3.addWidget(self.btn_PA, 0, 2, 1, 1)
        self.btn_dividir = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dividir.sizePolicy().hasHeightForWidth())
        self.btn_dividir.setSizePolicy(sizePolicy)
        self.btn_dividir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_dividir.setObjectName("btn_dividir")
        self.gridLayout_3.addWidget(self.btn_dividir, 2, 5, 1, 1)
        self.btn_resta = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_resta.sizePolicy().hasHeightForWidth())
        self.btn_resta.setSizePolicy(sizePolicy)
        self.btn_resta.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_resta.setObjectName("btn_resta")
        self.gridLayout_3.addWidget(self.btn_resta, 3, 5, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout_3.addWidget(self.btn_3, 4, 4, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout_3.addWidget(self.btn_6, 3, 4, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout_3.addWidget(self.btn_5, 3, 2, 1, 1)
        self.btn_multiplicar = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_multiplicar.sizePolicy().hasHeightForWidth())
        self.btn_multiplicar.setSizePolicy(sizePolicy)
        self.btn_multiplicar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.gridLayout_3.addWidget(self.btn_multiplicar, 0, 5, 1, 1)
        self.gridLayout_2.addWidget(self.frame_botones, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.contenedor)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.lbl_title.setText(_translate("MainWindow", "QtCalc"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_PC.setText(_translate("MainWindow", ")"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_point.setText(_translate("MainWindow", "."))
        self.btn_suma.setText(_translate("MainWindow", "+"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_borrar.setText(_translate("MainWindow", "C"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_PA.setText(_translate("MainWindow", "("))
        self.btn_dividir.setText(_translate("MainWindow", "÷"))
        self.btn_resta.setText(_translate("MainWindow", "-"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_multiplicar.setText(_translate("MainWindow", "×"))